### ISSUE TITLE
New business rules

### ISSUE THREAD

**Issue by pmaldonado-espol** [AlvaradoEddo/ISII-WORKSHOPS-ANTONELLA#6]
Dear support team, we are satisfied about your hard work during this last year. On this new year we want to be bigger and better. In the meeting with the Accounting Department and Business Intelligent Group, we proposed some changes with the intention of improving our service and getting more customers. The new business rule establishes: If the customer is married and has more than 30 years old but younger than 60, then $50 must be decreased to the base premium for each one, however if the customer is single, woman and older than 60 years old , she will receive a discount for around $50.

You need to know that all rules should be maintained how it was coming. Our request should be added to the existing one and the result should be calculated with all rules applied.

**Comment by AlvaradoEddo** [comment]
We have received your request and we are analyzing it.

**Comment by AlvaradoEddo** [comment]
we have categorized and tagged your suggestion to start development

**Comment by AlvaradoEddo** [comment]
I proceed to assign tasks:
@davalbra : will be the one that analyzes the request
@GBaquer25 : will be the developer
@KeylaFrancoH : will be the tester of the program

**Comment by davalbra** [comment]
@pmaldonado-espol  the analysis has been done 
[AnalysisReport.docx](https://github.com/AlvaradoEddo/ISII-WORKSHOPS-ANTONELLA/files/10471379/AnalysisReport.docx)

[AnalysisReport.pdf](https://github.com/AlvaradoEddo/ISII-WORKSHOPS-ANTONELLA/files/10442148/AnalysisReport.pdf)

**Comment by pmaldonado-espol** [comment]
> @pmaldonado-espol the analysis has been done
> [AnalysisReport.pdf](https://github.com/AlvaradoEddo/ISII-WORKSHOPS-ANTONELLA/files/10442148/AnalysisReport.pdf)

It’s Okay.

**Comment by GBaquer25** [comment]
The code has been developed with the new rules with the issues management branch, @KeylaFrancoH Can you test the code please?
https://github.com/AlvaradoEddo/ISII-WORKSHOPS-ANTONELLA/blob/ff15136e09622ee6e5f52a2f71737f3236e6a816/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java#L45-L52

**Comment by KeylaFrancoH** [comment]
I've tested the code and all the tests have passed, I attach the file of the unit test and system test

[unit-system test ANTONELLA.pdf](https://github.com/AlvaradoEddo/ISII-WORKSHOPS-ANTONELLA/files/10471384/unit-system.test.ANTONELLA.pdf)

**Comment by KeylaFrancoH** [comment]
@pmaldonado-espol , I attach the acceptnce testing plan for the newest rules and also some instrucction to run it if you want to proof  it . Can you review our accptance testing plan?

If you agree with our solution, let us know
[ACEPTANCE TESTING ANTONELLA IM.pdf](https://github.com/AlvaradoEddo/ISII-WORKSHOPS-ANTONELLA/files/10459939/ACEPTANCE.TESTING.ANTONELLA.IM.pdf)

**Comment by pmaldonado-espol** [comment]
> @pmaldonado-espol , I attach the acceptnce testing plan for the newest rules and also some instrucction to run it if you want to proof it . Can you review our accptance testing plan?
> 
> If you agree with our solution, let us know [ACEPTANCE TESTING ANTONELLA IM.pdf](https://github.com/AlvaradoEddo/ISII-WORKSHOPS-ANTONELLA/files/10459939/ACEPTANCE.TESTING.ANTONELLA.IM.pdf)

The changes requested were successfully implemented.

**Comment by AlvaradoEddo** [comment]
Good afternoon @pmaldonado-espol,  the requested request has been made correctly by @GBaquer25, so I proceed to mark the process as verified.  Later, she will be in charge of launching a new version of the system, so that he can do the tests on his own.

**Comment by GBaquer25** [comment]
Good afternoon @pmaldonado-espol. All changes have been done.
We have created an executable program, in orden to download it and use it, please, go to https://github.com/AlvaradoEddo/ISII-WORKSHOPS-ANTONELLA/releases/tag/v1.0.0  In there is described the requirements and the steps to follow and run the program. We will expecting if you need more specifications.

**Comment by AlvaradoEddo** [comment]
@pmaldonado-espol , have you been able to use the software? If so, are you satisfied with our solution or what changes do we have to make?

**Comment by pmaldonado-espol** [comment]
No more changes are needed, thank you.

**Comment by KeylaFrancoH** [comment]
@pmaldonado-espol Thank you, we are going to proceed to close the issue.

**Comment by GBaquer25** [comment]
Thank you @pmaldonado-espol
